### ISSUE TITLE
Error message includes html

### ISSUE THREAD

**Issue by captDaylight** [revolunet/react-mailchimp-subscribe#14]
When I get an error message it's including html. For example on duplicate email:

```
myemail@gmail.com is already subscribed to list INFURA News. <a href="https://infura.us14.list-manage.com/subscribe/send-email?e=cGF1bC5jaHJpc3RvcGhlNkBnbWFpbC5jb20%3D&u=7bec10aa5be97e80fcb0e7c52&id=13433031de">Click here to update your profile</a>
```

How are others handling this? In the demo it seems the error message is just being dropped in as a string.

**Comment by revolunet** [comment]
Hi,

You should use `dangerouselySetInnerHTML` in your form. I've just patched the demo form to handle this, and you can get it with `v2.0.2`
