### ISSUE TITLE
Form doesnt accept emails that contain '+'

### ISSUE THREAD

**Issue by cdinnison** [revolunet/react-mailchimp-subscribe#2]
As a user, if I try to put an email like john+test@gmail.com the form does not accept it. This is a common use case for people using one email to sign up for various services (i.e john+facebook@gmail.com). Any plans to accept this?

**Comment by revolunet** [comment]
good catch thanks ! fixes in https://github.com/revolunet/react-mailchimp-subscribe/releases/tag/v1.0.2
