### ISSUE TITLE
CORB blocked response on localhost

### ISSUE THREAD

**Issue by retzion** [revolunet/react-mailchimp-subscribe#20]
When I run your demo locally, it works great. When I copied my mailchimp web form URL to the project the request is now blocked.

`Cross-Origin Read Blocking (CORB) blocked cross-origin response https://sohotokenlabs.us19.list-manage.com/subscribe?u=5ab64f1e30494af6c10c92f55&id=208b2b428b&EMAIL=email%40address.com&c=__jp0 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

**Comment by retzion** [comment]
Never mind! The URL was wrong. I used the URL of the published form and found in another packages documentation that it needs to be the POST URL + `u` & `id` querystring params. All good now.

**Comment by mohamadelhinamy** [comment]
how did you change the method from get to post? @retzion
