### ISSUE TITLE
Double opt-in

### ISSUE THREAD

**Issue by grazianodev** [revolunet/react-mailchimp-subscribe#27]
Hello, 

thank you for this project, very quick and easy to implement. I was wondering if it is possible to enable double opt-in sign-ups, so that users are not immediately subscribed but receive an email to confirm their subscription instead. 

I read [here](https://stackoverflow.com/questions/31251271/realize-mailchimp-double-opt-in-with-api-3-0) that it should be enough to mark the user's status as "pending" rather than "subscribed".

**Comment by jp-signum** [comment]
this is actually a setting you must change in mailchimp when setting up your audience. Each audience(list) has its own opt-in setting ... simply search in their help section while logged in to your account and it will take you too yours

**Comment by revolunet** [comment]
thanks @jp-signum
