### ISSUE TITLE
Fix cookie in request for future chrome versions

### ISSUE THREAD

**Issue by Metashaker** [revolunet/react-mailchimp-subscribe#48]
This is still not an issue, bit will be in future Chrome verisons. I get the following warning after I succesfully suscribe users to my newsletter:
A cookie associated with a cross-site resource at https://list-manage.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.

**Comment by revolunet** [comment]
Well, this is from mailchimp so this cannot be fixed here unless they provide a real API to add subscribers

**Comment by Metashaker** [comment]
Okok, will bring it to their attention!
