### ISSUE TITLE
Compatibility with React 17

### ISSUE THREAD

**Issue by raphaelpinel** [revolunet/react-mailchimp-subscribe#58]
I just installed react-mailchimp-subscribe and got this error

npm ERR! Could not resolve dependency:
npm ERR! peer react@"15||16" from react-mailchimp-subscribe@2.1.1
npm ERR! node_modules/react-mailchimp-subscribe
npm ERR!   react-mailchimp-subscribe@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

I then installed with `npm i react-mailchimp-subscribe --force`

I have not tested yet if there are some issues.

But it would be nice if React 17 would be supported out of the box.

**Comment by revolunet** [comment]
Thanks for reporting, should be fixed in release 2.1.3
