### ISSUE TITLE
what xxxx? before 

### ISSUE THREAD

**Issue by gananggww** [revolunet/react-mailchimp-subscribe#8]
what xxxx?  before us13
`action: '//xxxx.us13.list-manage.com/subscribe/post?u=695fze434a101fd2a718afddde8&id=72al97ece5'`

**Comment by revolunet** [comment]
Of course you need to replace my url with your one :)

**Comment by gananggww** [comment]
where can i put my apikey and listID?

**Comment by gananggww** [comment]
please, i need more documentation

**Comment by revolunet** [comment]
So you take the README example, put it in your app, and replace the "action" value with your own mailchimp form url, that you can get from their interface, that should look like [that](https://daks2k3a4ib2z.cloudfront.net/55e66dd8b5daada24f333566/56c4d83de53a13b51727868c_mailchimp-form-action.png)

(I assume you now react, npm, webpack)

**Comment by gananggww** [comment]
oke thx. how can i custom a textfield and submit button sir?

**Comment by gananggww** [comment]
yeah i can styling...
how can i trigered onClick after subscribed

**Comment by revolunet** [comment]
there is no succes/error/callback at the moment but contributions are welcome.

this would involve adding a `this.props.onSuccess()` here : https://github.com/revolunet/react-mailchimp-subscribe/blob/master/src/index.js#L42 and same for errors.
